### ISSUE TITLE
Dependancy 'codemetar' was removed from CRAN

### ISSUE THREAD

**Issue by DirkMittelstrass** [R-Lum/RLumBuild#2]
Your package depends on [codemetar](https://cran.r-project.org/web/packages/codemetar/index.html). But that package was removed from CRAN which breaks the installation of `RLumBuild`. Installing `codemetar` from [CRAN archive](https://cran.r-project.org/src/contrib/Archive/codemetar/) does not fix the problem.

**Comment by RLumSK** [comment]
@DirkMittelstrass Sorry, I was not aware of it, it happens just seven days ago. You can install codemetar from GitHub though, the developers working on a fix: https://github.com/ropensci/codemetar

Besides, I don't understand why installing it from the CRAN archives does not fix the problem. Did you restart the R session?

**Comment by DirkMittelstrass** [comment]
Sorry my fault. Installing the archived package failed for unknown reasons and I missed the error message. But installing `codemetar `directly from github worked:

`devtools::install_github("ropensci/codemetar@master")`

**Comment by RLumSK** [comment]
Great, thanks for the feedback!
